import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {AnalystStore} from '../lib/analyst_store.mjs';

async function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.on('error',reject);server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(()=>resolve(port))})})}

test('HTTP analyst register rejects anonymous writes and records a separate review',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-api-')),dbPath=path.join(dir,'private','analyst.sqlite');
  let child;
  try{
    const store=new AnalystStore(dbPath),analyst=store.createOperator('api_analyst','API Analyst','analyst'),reviewer=store.createOperator('api_reviewer','API Reviewer','reviewer'),otherAnalyst=store.createOperator('other_analyst','Other Analyst','analyst');store.close();
    const port=await freePort(),base=`http://127.0.0.1:${port}`;
    child=spawn(process.execPath,['server.mjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),EVENT_ATLAS_ANALYST_DB:dbPath},stdio:'ignore'});
    let ready=false;for(let i=0;i<40;i++){try{const r=await fetch(base+'/api/health');if(r.ok){ready=true;break}}catch{}await new Promise(resolve=>setTimeout(resolve,100))}
    assert.equal(ready,true,'test server should start');
    const venue=JSON.parse(fs.readFileSync('data/venues.json','utf8')).venues[0];
    const payload={title:'Synthetic civic event',venueId:venue.id,startsAt:'2026-11-01T18:00:00.000Z',sourceUrl:'https://example.org/event',expectedAttendance:0};
    const post=async(token,body,origin)=>fetch(base+'/api/events',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(origin?{Origin:origin}:{})},body:JSON.stringify(body)});
    assert.equal((await post(null,payload)).status,401);
    assert.equal((await post(analyst,payload,'https://outside.example')).status,403);
    const malformed=await fetch(base+'/api/events',{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:'{'});assert.equal(malformed.status,400);
    const page=await fetch(base+'/');assert.match(page.headers.get('content-security-policy'),/frame-ancestors 'none'/);
    const createdResponse=await post(analyst,payload);assert.equal(createdResponse.status,201);const created=await createdResponse.json();assert.equal(created.owner,'API Analyst');assert.equal(created.status,'unreviewed');
    const list=await fetch(base+'/api/events',{headers:{Authorization:`Bearer ${reviewer}`}});assert.equal(list.status,200);assert.equal((await list.json()).items.length,1);
    const reviewResponse=await fetch(base+`/api/events/${created.id}/review`,{method:'POST',headers:{Authorization:`Bearer ${reviewer}`,'Content-Type':'application/json'},body:JSON.stringify({decision:'accepted_for_register',rationale:'Synthetic listing checked in this API test.'})});assert.equal(reviewResponse.status,201);
    assert.equal((await fetch(base+'/api/cases')).status,401);
    const votingChanges=await fetch(base+'/api/voting-changes?limit=1');assert.equal(votingChanges.status,200);assert.ok(Array.isArray((await votingChanges.json()).items));
    const votingList=await fetch(base+'/api/voting-locations?state=NY&limit=1');assert.equal(votingList.status,200);const votingListData=await votingList.json();assert.equal(typeof votingListData.staleCount,'number');assert.equal(typeof votingListData.items[0].connectorStatus,'string');
    const votingHistory=await fetch(base+'/api/voting-history?limit=1');assert.equal(votingHistory.status,200);const savedRuns=await votingHistory.json();assert.equal(savedRuns.verified,true);assert.ok(savedRuns.total>=0);if(savedRuns.total)assert.ok(savedRuns.items[0].archiveHash);
    const votingSnapshot=JSON.parse(fs.readFileSync('data/voting_locations.json','utf8'));
    const healthySources=new Set(votingSnapshot.sources.filter(source=>source.status==='ok').map(source=>source.id));
    const voting=votingSnapshot.locations.find(site=>healthySources.has(site.sourceId));
    assert.ok(voting,'synthetic API case needs a healthy source record');
    const siteDetail=await fetch(base+`/api/voting-location/${encodeURIComponent(voting.id)}`);assert.equal(siteDetail.status,200);assert.equal((await siteDetail.json()).source.id,voting.sourceId);
    const caseInput={subjectType:'voting_site',subjectId:voting.id,purpose:'Protective review of a sourced voting site.',authority:'Synthetic election office',openingRationale:'An analyst needs to document a cited observation for review.'};
    const openedResponse=await fetch(base+'/api/cases',{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify(caseInput)});assert.equal(openedResponse.status,201);const opened=await openedResponse.json();assert.equal(opened.subject.id,voting.id);assert.equal(typeof opened.subject.connectorStatus,'string');assert.equal(typeof opened.subject.sourceDataStatus,'string');
    assert.equal((await fetch(base+`/api/cases/${opened.id}`,{headers:{Authorization:`Bearer ${reviewer}`}})).status,404);
    const grant=await fetch(base+`/api/cases/${opened.id}/reviewers`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify({reviewerId:'api_reviewer',rationale:'Assigned to review the synthetic voting case evidence.'})});assert.equal(grant.status,201);const grantRecord=await grant.json();
    const otherCaseList=await fetch(base+'/api/cases',{headers:{Authorization:`Bearer ${otherAnalyst}`}});assert.deepEqual((await otherCaseList.json()).items,[]);
    assert.equal((await fetch(base+`/api/cases/${opened.id}`,{headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    const assessmentInput={severity:'review_candidate',confidence:'low',analysis:'This synthetic site notice requires a current source check before any operational inference.',confidenceRationale:'The synthetic example has a single source and no independent corroboration.',impact:'Potential site disruption would need confirmation from election officials.',alternativeExplanations:'The cited notice may be stale or refer to routine site maintenance.',protectiveNexus:'The claim references the selected sourced voting location.',recommendation:'Confirm the notice with the responsible election office.',limitations:'No real-world site condition is established by this synthetic test.',evidence:[{url:'https://example.org/notice',observedAt:'2026-10-09T12:00:00Z',claim:'Synthetic site notice published.',relevance:'The notice names the selected site.',classification:'official_notice'}]};
    const assessmentResponse=await fetch(base+`/api/cases/${opened.id}/assessments`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify(assessmentInput)});assert.equal(assessmentResponse.status,201);const assessment=await assessmentResponse.json();assert.equal(assessment.automaticNotification,false);
    const revokeGrant=await fetch(base+`/api/case-reviewers/${grantRecord.id}/revoke`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify({rationale:'Synthetic voting review is paused while case access is checked.'})});assert.equal(revokeGrant.status,200);
    assert.equal((await fetch(base+`/api/cases/${opened.id}`,{headers:{Authorization:`Bearer ${reviewer}`}})).status,404);
    const blockedReview=await fetch(base+`/api/assessments/${assessment.id}/review`,{method:'POST',headers:{Authorization:`Bearer ${reviewer}`,'Content-Type':'application/json'},body:JSON.stringify({decision:'accepted_for_internal_review',rationale:'Synthetic review must be denied after case grant revocation.'})});assert.equal(blockedReview.status,400);
    const secondGrant=await fetch(base+`/api/cases/${opened.id}/reviewers`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify({reviewerId:'api_reviewer',rationale:'Synthetic voting review resumes with renewed case assignment.'})});assert.equal(secondGrant.status,201);
    assert.equal((await fetch(base+`/api/cases/${opened.id}/assessments`,{method:'POST',headers:{Authorization:`Bearer ${otherAnalyst}`,'Content-Type':'application/json'},body:JSON.stringify(assessmentInput)})).status,400);
    const assessmentReview=await fetch(base+`/api/assessments/${assessment.id}/review`,{method:'POST',headers:{Authorization:`Bearer ${reviewer}`,'Content-Type':'application/json'},body:JSON.stringify({decision:'accepted_for_internal_review',rationale:'Synthetic evidence and alternatives checked for this API test.'})});assert.equal(assessmentReview.status,201);
    const caseDetail=await fetch(base+`/api/cases/${opened.id}`,{headers:{Authorization:`Bearer ${reviewer}`}});const detail=await caseDetail.json();assert.equal(detail.assessments[0].status,'accepted_for_internal_review');assert.equal(detail.sourceDrift.status,'unchanged_since_intake');
    const nfl=JSON.parse(fs.readFileSync('data/sports_events.json','utf8')).events.find(event=>event.sourceId==='nfl');
    const nflCase=await fetch(base+'/api/cases',{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify({...caseInput,subjectType:'published_event',subjectId:nfl.id,purpose:'Protective review of a sourced NFL game.'})});
    assert.equal(nflCase.status,201);const nflOpened=await nflCase.json();assert.equal(nflOpened.subject.sourceId,'nfl');assert.equal(nflOpened.subject.operationalSnapshot.startsAtLocal,nfl.startsAtLocal);
    const nflGrant=await fetch(base+`/api/cases/${nflOpened.id}/reviewers`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`,'Content-Type':'application/json'},body:JSON.stringify({reviewerId:'api_reviewer',rationale:'Assigned to review the synthetic NFL event case and brief.'})});assert.equal(nflGrant.status,201);
    const nflDetail=await fetch(base+`/api/cases/${nflOpened.id}`,{headers:{Authorization:`Bearer ${reviewer}`}});assert.equal(nflDetail.status,200);assert.equal((await nflDetail.json()).sourceDrift.status,'unchanged_since_intake');
    const personPost=async(url,token,body)=>fetch(base+url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
    const scopeResponse=await personPost(`/api/cases/${nflOpened.id}/person-scopes`,analyst,{role:'team_official',protectiveNexus:'A synthetic team official is designated for this NFL event review.',lawfulAuthority:'Synthetic protective assignment authority',collectionPurpose:'Prepare a bounded synthetic protective briefing.',expiresAt:new Date(Date.now()+7*86400000).toISOString()});assert.equal(scopeResponse.status,201);const scope=await scopeResponse.json();
    assert.equal((await personPost(`/api/cases/${nflOpened.id}/person-scopes`,otherAnalyst,{role:'team_official',protectiveNexus:'A synthetic team official is designated for this NFL event review.',lawfulAuthority:'Synthetic protective assignment authority',collectionPurpose:'Prepare a bounded synthetic protective briefing.',expiresAt:new Date(Date.now()+7*86400000).toISOString()})).status,400);
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}/brief?context=none`,{headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    const personInput={displayName:'Jordan Example',role:'team_official',professionalRole:'Synthetic team president',designationSource:{url:'https://example.org/official',authority:'Synthetic team',observedAt:new Date().toISOString()},identityConfidence:'moderate',identityRationale:'Synthetic name and role match the cited professional record.',publicProfessionalFacts:[{claim:'Serves as synthetic team president.',sourceUrl:'https://example.org/official',observedAt:new Date().toISOString()}],retentionUntil:new Date(Date.now()+6*86400000).toISOString()};
    assert.equal((await personPost(`/api/person-scopes/${scope.id}/people`,analyst,personInput)).status,400);
    assert.equal((await personPost(`/api/person-scopes/${scope.id}/review`,reviewer,{decision:'approved',rationale:'The synthetic scope is event-specific and sufficiently bounded.'})).status,201);
    assert.equal((await personPost(`/api/person-scopes/${scope.id}/people`,otherAnalyst,personInput)).status,400);
    const personResponse=await personPost(`/api/person-scopes/${scope.id}/people`,analyst,personInput);assert.equal(personResponse.status,201);const person=await personResponse.json();
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}`)).status,401);
    const scopedDetail=await fetch(base+`/api/cases/${nflOpened.id}`,{headers:{Authorization:`Bearer ${reviewer}`}});assert.equal((await scopedDetail.json()).personScopes[0].people[0].id,person.id);
    assert.equal((await personPost(`/api/protected-people/${person.id}/review`,reviewer,{decision:'approved',rationale:'Synthetic identity and designation source were checked.'})).status,201);
    const briefResponse=await fetch(base+`/api/cases/${nflOpened.id}/brief?context=none`,{headers:{Authorization:`Bearer ${analyst}`}});assert.equal(briefResponse.status,200);const brief=await briefResponse.json();assert.equal(brief.status,'draft_internal_review_only');assert.deepEqual(brief.protectedPeople.map(item=>item.id),[person.id]);assert.equal(brief.protectedPeople[0].eventAttendance.state,'not_verified');assert.equal(brief.overallJudgment.severity,'not_synthesized');assert.ok(brief.gaps.some(item=>item.includes('Current public conditions')));assert.equal(brief.nflContext.evidence.event.id,nfl.id);assert.equal(brief.nflContext.evidence.picture.assessment.severity,'not_assessed');assert.equal(brief.changesSincePreviousBrief.evidenceChanges.state,'no_baseline');
    const savedResponse=await fetch(base+`/api/cases/${nflOpened.id}/brief-snapshots?context=none`,{method:'POST',headers:{Authorization:`Bearer ${analyst}`}});assert.equal(savedResponse.status,201);const saved=await savedResponse.json();assert.equal(saved.sequence,1);
    const comparedResponse=await fetch(base+`/api/cases/${nflOpened.id}/brief?context=none`,{headers:{Authorization:`Bearer ${analyst}`}});assert.equal(comparedResponse.status,200);const compared=await comparedResponse.json();assert.equal(compared.changesSincePreviousBrief.baseline,saved.id);assert.ok(['compared','partial'].includes(compared.changesSincePreviousBrief.evidenceChanges.state));assert.deepEqual(compared.changesSincePreviousBrief.evidenceChanges.reviewCues.added,[]);
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}/brief-snapshots?context=none`,{method:'POST',headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}/brief-snapshots`,{headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    assert.equal((await fetch(base+`/api/brief-snapshots/${saved.id}`)).status,401);
    assert.equal((await fetch(base+`/api/brief-snapshots/${saved.id}`,{headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    const savedRead=await fetch(base+`/api/brief-snapshots/${saved.id}`,{headers:{Authorization:`Bearer ${reviewer}`}});assert.equal((await savedRead.json()).brief.protectedPeople[0].id,person.id);
    assert.equal((await personPost(`/api/brief-snapshots/${saved.id}/review`,analyst,{decision:'accepted_for_internal_review',rationale:'Synthetic brief and source were checked.'})).status,400);
    assert.equal((await personPost(`/api/brief-snapshots/${saved.id}/review`,reviewer,{decision:'accepted_for_internal_review',rationale:'The synthetic saved version and cited sources were checked.'})).status,201);
    const savedList=await fetch(base+`/api/cases/${nflOpened.id}/brief-snapshots`,{headers:{Authorization:`Bearer ${analyst}`}});assert.equal((await savedList.json()).items[0].status,'accepted_for_internal_review');
    assert.equal((await fetch(base+'/api/cases',{headers:{Authorization:`Bearer ${analyst}`}})).status,200);
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}/access-log`,{headers:{Authorization:`Bearer ${reviewer}`}})).status,404);
    assert.equal((await fetch(base+`/api/cases/${nflOpened.id}/access-log`,{headers:{Authorization:`Bearer ${otherAnalyst}`}})).status,404);
    const accessResponse=await fetch(base+`/api/cases/${nflOpened.id}/access-log`,{headers:{Authorization:`Bearer ${analyst}`}});assert.equal(accessResponse.status,200);const access=(await accessResponse.json()).items;
    assert.ok(access.some(item=>item.action==='case.viewed'&&item.operatorId==='api_reviewer'));
    assert.ok(access.some(item=>item.action==='brief_snapshot.viewed'&&item.operatorId==='api_reviewer'&&item.resourceId===saved.id));
    assert.ok(access.some(item=>item.action==='brief_snapshot.listed'&&item.operatorId==='api_analyst'));
    assert.ok(access.some(item=>item.action==='case.listed'&&item.operatorId==='api_analyst'));
    assert.ok(access.some(item=>item.action==='case.access_log_viewed'&&item.operatorId==='api_analyst'));
    const me=await fetch(base+'/api/operators/me',{headers:{Authorization:`Bearer ${reviewer}`}});const result=await me.json();assert.equal(result.audit.verified,true);assert.ok(result.audit.entries>21);
  }finally{child?.kill();fs.rmSync(dir,{recursive:true,force:true})}
});
