import test from 'node:test';
import assert from 'node:assert/strict';
import {buildEventBrief} from '../lib/build_event_brief.mjs';

const event={id:'example:1',title:'Public event',startsAtLocal:'2026-10-10T12:00:00',endsAtLocal:null,timeZone:'America/New_York',status:'published-source; unreviewed',sourceUrl:'https://example.gov/event/1',sourceDataset:'https://example.gov/events',retrievedAt:'2026-10-09T00:00:00Z',venueId:null,organizer:null};
const place={id:'place:1',name:'Public park',address:null,lat:40,lon:-73};
const alert={id:'nws:1',headline:'Severe weather warning',severity:'Severe',urgency:'Immediate',effective:'2026-10-10T15:00:00Z',expires:'2026-10-10T17:00:00Z',url:'https://api.weather.gov/alerts/nws-1'};
const feeds={weather:{items:[alert],retrievedAt:1000,stale:false,error:null},earthquakes:{items:[{id:'quake:1',title:'Earthquake',url:'https://earthquake.usgs.gov/earthquakes/eventpage/1',time:1000}],retrievedAt:1000,stale:false,error:null},naturalEvents:{items:[],retrievedAt:1000,stale:false,error:null}};

test('brief distinguishes a source alert review candidate from an assessed threat',()=>{const brief=buildEventBrief(event,place,feeds,'2026-10-10T12:00:00Z');assert.equal(brief.reviewCandidates.length,1);assert.equal(brief.reviewCandidates[0].status,'unreviewed');assert.equal(brief.assessment.severity,'not_assessed');assert.equal(brief.assessment.confidence,'not_assessed');assert.equal(brief.observations[0].source,'nws');assert.equal(brief.observations[1].source,'usgs');assert.match(brief.observations[1].qualifier,/no impact/);assert.ok(brief.gaps.some(x=>x.includes('end time')))});
test('stale alert, cancelled event, and missing point do not create a protective review candidate',()=>{assert.equal(buildEventBrief(event,place,{...feeds,weather:{...feeds.weather,stale:true}}).reviewCandidates.length,0);assert.equal(buildEventBrief({...event,status:'cancelled in source'},place,feeds).reviewCandidates.length,0);const noPoint=buildEventBrief(event,{...place,lat:null,lon:null},null);assert.equal(noPoint.observations.length,0);assert.equal(noPoint.feeds.nws.state,'not_queried');assert.ok(noPoint.gaps.some(x=>x.includes('No source coordinates')))});
test('alert outside event window does not become a review candidate',()=>{const past={...event,endsAtLocal:'2026-10-10T13:00:00'};const later={...feeds,weather:{...feeds.weather,items:[{...alert,effective:'2026-10-10T20:00:00Z',expires:'2026-10-10T21:00:00Z'}]}};assert.equal(buildEventBrief(past,place,later).reviewCandidates.length,0);assert.equal(buildEventBrief(past,place,feeds).event.startUtc,'2026-10-10T16:00:00.000Z')});
