import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const venues=read('data/venues.json'),municipal=read('data/public_events.json'),sports=read('data/sports_events.json'),voting=read('data/voting_locations.json'),dns=read('data/dns_observations.json');
test('venue records have stable unique source IDs and plausible coordinates',()=>{const ids=new Set();for(const v of venues.venues){assert.ok(v.id&&v.source.endsWith(v.id));assert.ok(Number.isFinite(v.lat)&&v.lat>=-15&&v.lat<=72);assert.ok(Number.isFinite(v.lon)&&v.lon>=-180&&v.lon<=180);assert.ok(!ids.has(v.id));ids.add(v.id)}});
test('published events preserve source and link to source-derived place',()=>{for(const snapshot of [municipal,sports]){const places=new Set(snapshot.places.map(p=>p.id));for(const e of snapshot.events){assert.ok(e.title&&e.startsAtLocal&&e.timeZone&&e.sourceUrl);if(e.placeId)assert.ok(places.has(e.placeId));else assert.ok(!e.sourcePlace.name&&!Number.isFinite(e.sourcePlace.lat));assert.ok(e.sourceId&&e.retrievedAt)}}});
test('NFL demo snapshot covers the US regular-season games without old Buffalo coordinates',()=>{const source=sports.sources.find(s=>s.id==='nfl'),games=sports.events.filter(e=>e.sourceId==='nfl'),places=new Map(sports.places.map(p=>[p.id,p]));assert.equal(source.status,'ok');assert.equal(source.reportedTotal,272);assert.equal(source.excludedInternational,9);assert.equal(games.length,263);assert.equal(new Set(games.map(g=>g.id)).size,263);assert.equal(new Set(games.map(g=>g.placeId)).size,30);for(const game of games){assert.match(game.sourceUrl,/espn\.com\/nfl\/game/);assert.equal(game.participants.length,2);assert.match(places.get(game.placeId).address,/, [A-Z]{2}, USA$/)}const buffalo=[...places.values()].find(p=>p.sourceIds.includes('nfl')&&p.name==='Highmark Stadium');assert.equal(buffalo.lat,null);assert.equal(buffalo.lon,null)});
test('DNS addresses are observations, never venue ownership assertions',()=>{assert.match(dns.caution,/not attributed/i);for(const h of dns.hosts){assert.match(h.attribution,/unverified/i);for(const ip of h.addresses){assert.match(ip,/^\d+\.\d+\.\d+\.\d+$/);assert.ok(!ip.startsWith('10.')&&!ip.startsWith('127.')&&!ip.startsWith('192.168.'))}}});
test('scan targets remain empty until individually authorized',()=>{const c=read('data/scan_targets.json');assert.deepEqual(c.targets,[]);assert.equal(c.authorizationReference,null)});
test('voting sites retain jurisdiction, type, source, and election-specific status',()=>{const ids=new Set(),sources=new Set(voting.sources.map(x=>x.id));assert.ok(voting.locations.length>18700);for(const v of voting.locations){assert.ok(!ids.has(v.id));ids.add(v.id);assert.ok(sources.has(v.sourceId));assert.ok(['NY','DC','MD','PA','NC','WA','SC','WV','DE','FL','CT','NJ'].includes(v.jurisdiction));assert.ok(['election_day_polling_place','election_day_vote_center','early_vote_center','voting_center','ballot_drop_box','secure_ballot_intake_station'].includes(v.type));if(['md-early','md-drop-box','nc-early-nov-2026','sc-early-general-2026','wv-early-general-2026','de-early-general-2026','de-election-day-general-2026','fl-early-general-2026','fl-intake-general-2026','ct-early-general-2026','nj-early-general-2026'].includes(v.sourceId))assert.equal(v.lat,null);else assert.ok(Number.isFinite(v.lat)&&Number.isFinite(v.lon));assert.ok(v.sourceRecordUrl.startsWith('https://'));assert.match(v.sourceDataStatus,/verify|confirm/i)}assert.ok(voting.locations.some(v=>v.type==='ballot_drop_box'));assert.ok(voting.locations.some(v=>v.datesOpen));assert.equal(voting.locations.filter(v=>v.sourceId==='md-election-day').length,1463)});
test('Maryland PDF extraction excludes publisher footer text from site names',()=>{for(const v of voting.locations.filter(x=>x.jurisdiction==='MD'))assert.doesNotMatch(v.name,/151 West Street|Local - 410\.269|Page \d+/)});

test('Pennsylvania source preserves precinct rows and geocode limitations',()=>{const rows=voting.locations.filter(v=>v.sourceId==='pa-polling-may-2026');assert.equal(rows.length,9148);assert.equal(voting.sources.find(s=>s.id==='pa-polling-may-2026')?.status,'ok');assert.ok(rows.every(v=>v.precinct&&v.county&&v.street&&v.sourceRecordUrl.includes('OBJECTID')&&v.datesOpen===''&&v.hours===''));assert.ok(rows.some(v=>v.geocodeMatchScore!==null));assert.ok(new Set(rows.map(v=>`${v.name}|${v.street}|${v.city}`)).size<rows.length)});

test('North Carolina November early-vote PDF retains all counties and date-hour pairs',()=>{const rows=voting.locations.filter(v=>v.sourceId==='nc-early-nov-2026');assert.equal(rows.length,371);assert.equal(new Set(rows.map(v=>v.county)).size,100);assert.equal(voting.sources.find(s=>s.id==='nc-early-nov-2026')?.status,'ok');for(const row of rows){assert.equal(row.lat,null);assert.equal(row.lon,null);assert.ok(row.sourcePage>=1&&row.sourcePage<=46);assert.ok(row.schedule.length>0);assert.ok(row.schedule.every(pair=>pair.dates&&pair.hours));assert.match(row.sourceRecordUrl,/\.pdf#page=\d+$/)}});
test('Washington November list retains drop boxes and voting centers without inventing hours',()=>{const rows=voting.locations.filter(v=>v.sourceId==='wa-nov-2026-sites');assert.equal(rows.length,655);assert.equal(new Set(rows.map(v=>v.county)).size,39);assert.equal(rows.filter(v=>v.type==='ballot_drop_box').length,594);assert.equal(rows.filter(v=>v.type==='voting_center').length,61);assert.equal(voting.sources.find(s=>s.id==='wa-nov-2026-sites')?.status,'ok');assert.ok(rows.every(v=>v.street&&v.sourceRow>=2&&v.datesOpen===''&&v.hours===''));assert.ok(rows.some(v=>v.description));});

test('South Carolina official general-election list retains 46 counties and published statewide schedule',()=>{const rows=voting.locations.filter(v=>v.sourceId==='sc-early-general-2026');assert.equal(rows.length,140);assert.equal(new Set(rows.map(v=>v.county)).size,46);assert.equal(voting.sources.find(s=>s.id==='sc-early-general-2026')?.status,'ok');for(const row of rows){assert.equal(row.lat,null);assert.equal(row.lon,null);assert.equal(row.type,'early_vote_center');assert.match(row.datesOpen,/October 19–31, 2026/);assert.match(row.hours,/8:30 a.m.–6:00 p.m./);assert.match(row.sourceRecordUrl,/scvotes\.gov\/voters\/early-voting\/#/);}});
test('West Virginia general early-voting list preserves county hours and late-opening sites',()=>{const rows=voting.locations.filter(v=>v.sourceId==='wv-early-general-2026');assert.equal(rows.length,99);assert.equal(new Set(rows.map(v=>v.county)).size,55);assert.equal(voting.sources.find(s=>s.id==='wv-early-general-2026')?.status,'ok');assert.equal(rows.filter(v=>v.datesOpen==='October 27–31, 2026').length,4);for(const row of rows){assert.equal(row.lat,null);assert.equal(row.lon,null);assert.equal(row.type,'early_vote_center');assert.match(row.hours,/Mon–Fri .*; Saturday /);assert.match(row.street,/WV \d{5}/);assert.match(row.sourceUrl,/sos\.wv\.gov\/early-voting-locations/);}});
test('Delaware general-election tables retain distinct district mappings and early-vote schedule',()=>{const early=voting.locations.filter(v=>v.sourceId==='de-early-general-2026'),day=voting.locations.filter(v=>v.sourceId==='de-election-day-general-2026');assert.equal(early.length,19);assert.equal(day.length,533);assert.deepEqual(new Set(early.map(v=>v.county)),new Set(['Kent','New Castle','Sussex']));assert.deepEqual(new Set(day.map(v=>v.county)),new Set(['Kent','New Castle','Sussex']));assert.equal(voting.sources.find(s=>s.id==='de-election-day-general-2026')?.sourceDuplicateLines,7);for(const row of early){assert.equal(row.lat,null);assert.equal(row.type,'early_vote_center');assert.match(row.datesOpen,/October 22–24/);assert.match(row.hours,/7 a\.m\.–7 p\.m\./)}for(const row of day){assert.equal(row.lat,null);assert.equal(row.type,'election_day_polling_place');assert.match(row.precinct,/^\d{2}-\d{2}$/);assert.equal(row.datesOpen,'November 3, 2026');assert.equal(row.hours,'7 a.m.–8 p.m.')}});
test('Florida 2026 General Election PDFs retain statewide early-vote schedules and additional intake stations',()=>{const early=voting.locations.filter(v=>v.sourceId==='fl-early-general-2026'),intake=voting.locations.filter(v=>v.sourceId==='fl-intake-general-2026');assert.equal(early.length,464);assert.equal(intake.length,66);assert.equal(new Set(early.map(v=>v.county)).size,67);assert.equal(voting.sources.find(s=>s.id==='fl-early-general-2026')?.status,'ok');assert.equal(voting.sources.find(s=>s.id==='fl-intake-general-2026')?.status,'ok');assert.equal(early.filter(v=>!v.postal).length,43);assert.ok(early.some(v=>v.sourceScheduleAnomalies.length));for(const row of early){assert.equal(row.lat,null);assert.equal(row.type,'early_vote_center');assert.ok(row.schedule.length>0);assert.ok(row.schedule.every(item=>/^2026-(10|11)-/.test(item.dates)&&item.hours));assert.match(row.sourceFile,/2026 GE\.pdf$/);assert.ok(row.sourcePage>0)}assert.equal(intake.filter(row=>row.datesOpen&&row.hours).length,2);for(const row of intake){assert.equal(row.lat,null);assert.equal(row.type,'secure_ballot_intake_station');if(row.datesOpen)assert.match(row.datesOpen,/^2026-11-0[23]$/)}});
test('Connecticut rolling 2026 state-election list preserves published municipal sites without invented schedules',()=>{const rows=voting.locations.filter(v=>v.sourceId==='ct-early-general-2026'),source=voting.sources.find(s=>s.id==='ct-early-general-2026');assert.equal(rows.length,174);assert.equal(new Set(rows.map(v=>v.county)).size,169);assert.equal(source?.status,'ok');assert.equal(source?.dataEditedAt,'2026-10-08');assert.match(source.dataset,/portal\.ct\.gov.*november-3--2026\.pdf/);for(const row of rows){assert.equal(row.type,'early_vote_center');assert.equal(row.lat,null);assert.equal(row.lon,null);assert.equal(row.datesOpen,'');assert.equal(row.hours,'');assert.match(row.street,/\d{5}/);assert.ok(row.sourcePage>=1&&row.sourcePage<=5)}});
test('New Jersey general-election early-voting page retains all counties and marks incomplete addresses',()=>{const rows=voting.locations.filter(v=>v.sourceId==='nj-early-general-2026'),source=voting.sources.find(s=>s.id==='nj-early-general-2026');assert.equal(rows.length,171);assert.equal(new Set(rows.map(v=>v.county)).size,21);assert.equal(source?.status,'ok');assert.equal(source?.dataEditedAt,'2026-09-17');assert.equal(rows.filter(v=>!v.postal).length,6);for(const row of rows){assert.equal(row.type,'early_vote_center');assert.equal(row.lat,null);assert.equal(row.lon,null);assert.equal(row.datesOpen,'October 24–November 1, 2026');assert.match(row.hours,/Monday–Saturday/);assert.match(row.sourceRecordUrl,/vote-early-voting\.shtml#/);assert.match(row.municipalityLabel,/^EVC\b/)}});
