import test from 'node:test';
import assert from 'node:assert/strict';
import {eventMonitoringPlan} from '../site/event_monitoring_plan.js';
import {publicEventAlertsSummary} from '../site/public_event_alerts.js';
const now=Date.parse('2026-10-10T16:00:00Z');
const game={id:'test',title:'Concert',eventType:'concert',kickoff:'2026-10-10T17:00:00Z',endsAt:'2026-10-10T19:00:00Z',venue:{name:'Park',address:'New York, NY, USA',lat:40.8,lon:-74},sourceUrl:'https://example.com/event'};
const feature=(changes={})=>({id:'urn:test:alert',properties:{id:'urn:test:alert',status:'Actual',messageType:'Alert',event:'Wind Advisory',headline:'Advisory at park',sent:'2026-10-10T15:00:00Z',onset:'2026-10-10T15:30:00Z',expires:'2026-10-10T20:00:00Z',senderName:'NWS',...changes}});
const data=features=>({type:'FeatureCollection',features});
test('lifecycle uses explicit end time and does not invent NFL completion',()=>{assert.equal(eventMonitoringPlan(game,now).phase,'Before the event');assert.equal(eventMonitoringPlan(game,now+7200000).phase,'During the published event period');assert.equal(eventMonitoringPlan(game,now+14400000).phase,'After the event');assert.equal(eventMonitoringPlan({...game,endsAt:undefined},now+14400000).phase,'Event status needs confirmation');});
test('actual current overlapping official alerts keep publication time and source instructions',()=>{const s=publicEventAlertsSummary(game,data([feature({instruction:'Secure loose objects.'})]),now);assert.equal(s.items.length,1);assert.equal(s.items[0].sourceAt,'2026-10-10T15:00:00.000Z');assert.equal(s.items[0].action,'Secure loose objects.');assert.ok(s.items[0].sourceUrl.startsWith('https://api.weather.gov/alerts/'));assert.match(s.items[0].basis,/daily operating hours.*not independently verified/);});
test('expired, cancelled, test and unrelated-time alerts do not become event concerns',()=>{const s=publicEventAlertsSummary(game,data([feature({expires:'2026-10-10T15:59:00Z'}),feature({messageType:'Cancel'}),feature({status:'Test'}),feature({onset:'2026-10-11T17:00:00Z',expires:'2026-10-11T19:00:00Z'})]),now);assert.equal(s.items.length,0);});
test('unknown timestamps are excluded and malformed feed is a failure',()=>{const s=publicEventAlertsSummary(game,data([feature({expires:null})]),now);assert.equal(s.items.length,0);assert.equal(s.sources[0].state,'partial response');assert.throws(()=>publicEventAlertsSummary(game,{features:[]},now));});

test('cached weather observations expire without converting failed coverage into a successful check',async()=>{const {setAdditionalSummary,getAdditionalSummary,clearAdditionalSummary}=await import('../site/event_catalog.js');setAdditionalSummary(game.id,{checkedAt:Date.now(),label:'1 weather concern',items:[{validUntil:new Date(Date.now()-1000).toISOString()}],urgent:[],sources:[]});assert.equal(getAdditionalSummary(game).items.length,0);setAdditionalSummary(game.id,{checkedAt:Date.now(),label:'Monitoring not started',items:[],urgent:[],sources:[{name:'NWS',state:'source failed'}]});assert.equal(getAdditionalSummary(game).label,'Monitoring not started');clearAdditionalSummary(game.id);});
