import http from 'node:http';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildEventBrief} from './lib/build_event_brief.mjs';
import {buildInternalCaseBrief,compareBriefSnapshots} from './lib/build_internal_case_brief.mjs';
import {buildNflCaseContext} from './lib/build_nfl_case_context.mjs';
import {LOCAL_MODEL,buildLocalAiPacket,generateLocalAiDraft,localAiDraftHash} from './lib/local_ai_brief.mjs';
import {AnalystStore} from './lib/analyst_store.mjs';
import {normalizeGroundZone,screenControlledGroundZones} from './lib/controlled_ground_zone.mjs';
import {projectVotingSite,caseVotingDrift} from './lib/voting_snapshot.mjs';
import {projectEvent,caseEventDrift} from './lib/event_snapshot.mjs';
import {readVotingHistory} from './lib/voting_history.mjs';
import {mbtaFoxboroAlertsUrl,summarizeMbtaFoxboroAlerts} from './site/mbta_foxboro_alerts.js';
import {mbtaFoxboroSchedulesUrl,summarizeMbtaFoxboroSchedules} from './site/mbta_foxboro_schedules.js';
import {mbtaFoxboroPredictionsUrl,summarizeMbtaFoxboroPredictions} from './site/mbta_foxboro_predictions.js';
import {fetchSelectedGame} from './site/espn_game_summary.js';
import {selectKickoffForecast,selectEventHourForecast} from './site/nws_forecast.js';
import {buildEonetNflSnapshot} from './site/eonet_nfl.js';
import {soundTransitAlertsFeed,summarizeSoundTransitAlerts} from './site/sound_transit_alerts.js';
import {seattleFireAggregateQuery,seattleFireMetadataUrl,summarizeSeattleFireAggregate} from './site/seattle_fire_aggregate.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT||4173);
const snapshot=JSON.parse(await fs.readFile(path.join(root,'data/venues.json'),'utf8'));
const venues=snapshot.venues;
const byId=new Map(venues.map(v=>[v.id,v]));
const municipal=JSON.parse(await fs.readFile(path.join(root,'data/public_events.json'),'utf8'));
const sports=JSON.parse(await fs.readFile(path.join(root,'data/sports_events.json'),'utf8'));
async function readSiteSnapshot(name){try{return JSON.parse(await fs.readFile(path.join(root,'site',name),'utf8'))}catch{return null}}
const [nflSchedule,nflGround,nflAirspace,nflTfr,nflCameras,nflRoads,nflSpc,nflWpcRain,nflEonet,nflNews,nflGameArticles,nflNtas,nflIndianapolis,nflCharlotte,nflArlington,nflDenver,nflPhillyAlerts,nflPhillyPermits,nflGreenBayAlerts,nflLambeauPlan,nflPackersRelease,nflPatriotsPreview,nflJetsGuide,nflSeahawksGuide,nflTitansGuide,nflFalconsGuide,nflSaintsGuide,nflNortaAlerts,nflMartaRail,nflMartaAlertPreview,nflGeorgiaTraffic,nflSoundTransitSeahawks,nflSoundTransitAlerts,nflSeattleFireAggregate,nflNashvillePoliceCount,nflSepta,nflNjTransitRail]=await Promise.all(['nfl.json','ground_footprints.json','seams.json','tfr.json','cameras.json','roads.json','spc_outlooks.json','wpc_rain_outlooks.json','eonet.json','news.json','game_articles.json','ntas.json','indianapolis_public_safety.json','charlotte_public_safety.json','arlington_public_safety.json','denver_public_safety.json','philly_city_alerts.json','philly_lane_permits.json','green_bay_alerts.json','lambeau_gameday.json','packers_game_release.json','patriots_game_preview.json','jets_gameday_guide.json','seahawks_gameday.json','titans_gameday.json','falcons_gameday.json','saints_gameday.json','norta_alerts.json','marta_rail.json','marta_alert_preview.json','georgia_traffic.json','sound_transit_seahawks.json','sound_transit_alerts.json','seattle_fire_aggregate.json','nashville_police_count.json','septa_b_alerts.json','njtransit_event_rail.json'].map(readSiteSnapshot));
const nflSnapshots={schedule:nflSchedule,ground:nflGround,airspace:nflAirspace,tfr:nflTfr,cameras:nflCameras,roads:nflRoads,spc:nflSpc,wpcRain:nflWpcRain,eonet:nflEonet,news:nflNews,gameArticles:nflGameArticles,ntas:nflNtas,indianapolis:nflIndianapolis,charlotte:nflCharlotte,arlington:nflArlington,denver:nflDenver,phillyAlerts:nflPhillyAlerts,phillyPermits:nflPhillyPermits,greenBayAlerts:nflGreenBayAlerts,lambeauPlan:nflLambeauPlan,packersGameRelease:nflPackersRelease,patriotsGamePreview:nflPatriotsPreview,jetsGamedayGuide:nflJetsGuide,seahawksGameday:nflSeahawksGuide,titansGameday:nflTitansGuide,falconsGameday:nflFalconsGuide,saintsGameday:nflSaintsGuide,nortaAlerts:nflNortaAlerts,martaRail:nflMartaRail,martaAlertPreview:nflMartaAlertPreview,georgiaTraffic:nflGeorgiaTraffic,soundTransitSeahawks:nflSoundTransitSeahawks,soundTransitAlerts:nflSoundTransitAlerts,seattleFireAggregate:nflSeattleFireAggregate,nashvillePoliceCount:nflNashvillePoliceCount,septa:nflSepta,njTransitRail:nflNjTransitRail};
const voting=JSON.parse(await fs.readFile(path.join(root,'data/voting_locations.json'),'utf8'));
const votingHistory=readVotingHistory(path.join(root,'data/voting_history'));
const votingById=new Map(voting.locations.map(v=>[v.id,v]));
const published={retrievedAt:[municipal.retrievedAt,sports.retrievedAt].sort().at(-1),coverageNote:municipal.coverageNote+' '+sports.coverageNote,sources:[...municipal.sources,...sports.sources],places:[...municipal.places,...sports.places],events:[...municipal.events,...sports.events]};
const eventChanges=[...(municipal.changeSet?.items||[]),...(sports.changeSet?.items||[])];
const publicById=new Map(published.events.map(e=>[e.id,e]));
const placeById=new Map(published.places.map(p=>[p.id,p]));
const dnsSnapshot=JSON.parse(await fs.readFile(path.join(root,'data/dns_observations.json'),'utf8'));
const dnsByVenue=new Map();for(const h of dnsSnapshot.hosts)for(const id of h.venueIds)dnsByVenue.set(id,h);
const eventsFile=path.join(root,'data/events.json');
const legacyEvents=JSON.parse(await fs.readFile(eventsFile,'utf8').catch(()=>'[]'));
if(legacyEvents.length)throw Error('Legacy analyst events require a reviewed migration before enabling the controlled register');
const analystStore=new AnalystStore(process.env.EVENT_ATLAS_ANALYST_DB||path.join(root,'data/private/analyst.sqlite'));
async function readBody(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>20000)throw Object.assign(Error('Request too large'),{statusCode:413})}try{return JSON.parse(body)}catch{throw Object.assign(Error('Invalid JSON'),{statusCode:400})}}
const cache=new Map();
const sources={nws:{name:'National Weather Service active alerts',url:'https://api.weather.gov/alerts/active',refreshMinutes:5,scope:'Point-specific public weather alerts',license:'Public federal data; review NWS API terms'},nwsForecast:{name:'NWS hourly forecast at event venue',url:'https://api.weather.gov/points',refreshMinutes:30,scope:'Kickoff-hour forecast when the event falls within the approximately seven-day forecast window and has a mapped point',license:'Public federal data; forecast is not a site impact assessment'},usgs:{name:'USGS earthquake GeoJSON',url:'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson',refreshMinutes:5,scope:'Recent earthquake observations; proximity is not an impact assessment',license:'Public federal data'},kev:{name:'CISA Known Exploited Vulnerabilities',url:'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',refreshMinutes:60,scope:'General cyber watchlist; requires verified asset match before event linkage',license:'Public federal data'},eonet:{name:'NASA EONET open natural events',url:'https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&limit=500',refreshMinutes:15,scope:'Curated natural event metadata; proximity is not an impact assessment',license:'Public NASA API; review source and metadata disclaimer'}};
async function remote(key,url,ttl){const old=cache.get(key);if(old&&Date.now()-old.at<ttl)return {...old,stale:false};try{const r=await fetch(url,{headers:{'User-Agent':'EventAtlas/0.4 (local prototype; contact: local operator)','Accept':'application/geo+json, application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();const out={at:Date.now(),data,error:null};cache.set(key,out);return {...out,stale:false}}catch(e){return old?{...old,stale:true,error:String(e)}:{at:null,data:null,stale:true,error:String(e)}}}
const securityHeaders={'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'self' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https://tile.openstreetmap.org; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"};
function send(res,code,obj){res.writeHead(code,{...securityHeaders,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function operator(req,res){const user=analystStore.authenticate(req.headers.authorization);if(!user)send(res,401,{error:'Operator token required'});return user}
function sameOrigin(req,res){const origin=req.headers.origin;if(origin&&origin!==`http://127.0.0.1:${port}`&&origin!==`http://localhost:${port}`){send(res,403,{error:'Cross-origin write denied'});return false}return true}
function distance(a,b,c,d){const r=Math.PI/180;const x=(d-b)*r*Math.cos((a+c)*r/2),y=(c-a)*r;return 6371*Math.hypot(x,y)}
async function context(v){const [weather,quakes,kev,eonet]=await Promise.all([remote('nws:'+v.id,`${sources.nws.url}?point=${v.lat},${v.lon}`,300000),remote('usgs',sources.usgs.url,300000),remote('kev',sources.kev.url,3600000),remote('eonet',sources.eonet.url,900000)]);const nwsAlerts=(weather.data?.features||[]).map(f=>({id:f.id,event:f.properties?.event,headline:f.properties?.headline,severity:f.properties?.severity,urgency:f.properties?.urgency,effective:f.properties?.effective,expires:f.properties?.expires,url:f.properties?.['@id']||f.id,description:f.properties?.description}));const near=(quakes.data?.features||[]).map(f=>({id:f.id,title:f.properties?.title,time:f.properties?.time,magnitude:f.properties?.mag,url:f.properties?.url,lat:f.geometry?.coordinates?.[1],lon:f.geometry?.coordinates?.[0]})).filter(f=>Number.isFinite(f.lat)&&distance(v.lat,v.lon,f.lat,f.lon)<=250).sort((a,b)=>distance(v.lat,v.lon,a.lat,a.lon)-distance(v.lat,v.lon,b.lat,b.lon)).slice(0,15);const natural=(eonet.data?.features||[]).map(f=>({id:f.properties?.id,title:f.properties?.title,date:f.properties?.date,url:f.properties?.link,category:f.properties?.categories?.map(c=>c.title).join(', '),lat:f.geometry?.coordinates?.[1],lon:f.geometry?.coordinates?.[0]})).filter(f=>Number.isFinite(f.lat)&&Number.isFinite(f.lon)&&distance(v.lat,v.lon,f.lat,f.lon)<=250).slice(0,15);const vulns=(kev.data?.vulnerabilities||[]).slice().sort((a,b)=>String(b.dateAdded).localeCompare(String(a.dateAdded))).slice(0,12).map(x=>({cve:x.cveID,vendor:x.vendorProject,product:x.product,name:x.vulnerabilityName,added:x.dateAdded}));return {venue:v,dns:dnsByVenue.get(v.id)||null,weather:{items:nwsAlerts,retrievedAt:weather.at,stale:weather.stale,error:weather.error},earthquakes:{items:near,retrievedAt:quakes.at,stale:quakes.stale,error:quakes.error},naturalEvents:{items:natural,retrievedAt:eonet.at,stale:eonet.stale,error:eonet.error},kev:{items:vulns,retrievedAt:kev.at,stale:kev.stale,error:kev.error,linkedToVenue:false}}}
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
async function kickoffForecast(event,place){
  if(event.sourceId!=='nfl')return null;
  if(event.timeTbd)return {status:'outside_window',reason:'Kickoff time has not been published'};
  const kickoff=Date.parse(event.startsAtLocal),hoursAway=(kickoff-Date.now())/3600000;
  if(!Number.isFinite(place?.lat)||!Number.isFinite(place?.lon))return {status:'unavailable',reason:'No reviewed venue coordinate; a forecast cannot be placed'};
  if(!Number.isFinite(kickoff)||hoursAway<0||hoursAway>168)return {status:'outside_window',reason:'Kickoff is outside the NWS hourly forecast window'};
  const pointUrl=sources.nwsForecast.url+'/'+place.lat+','+place.lon;
  const point=await remote('nws-point:'+place.id,pointUrl,86400000);
  const url=point.data?.properties?.forecastHourly;
  if(!url||new URL(url).origin!=='https://api.weather.gov')return {status:'unavailable',reason:point.error||'NWS did not supply an hourly endpoint',retrievedAt:point.at};
  const forecast=await remote('nws-forecast:'+place.id,url,1800000);
  const period=(forecast.data?.properties?.periods||[]).find(p=>Date.parse(p.startTime)<=kickoff&&kickoff<Date.parse(p.endTime));
  if(!period)return {status:'unavailable',reason:forecast.error||'No forecast period covers kickoff',retrievedAt:forecast.at,stale:forecast.stale};
  return {status:forecast.stale?'stale':'ok',startTime:period.startTime,endTime:period.endTime,temperature:period.temperature,temperatureUnit:period.temperatureUnit,shortForecast:period.shortForecast,windSpeed:period.windSpeed,windDirection:period.windDirection,probabilityOfPrecipitation:period.probabilityOfPrecipitation?.value??null,url,retrievedAt:forecast.at,stale:forecast.stale};
}
async function selectedNflForecast(game){
  if(!game||!Number.isFinite(game.venue?.lat)||!Number.isFinite(game.venue?.lon))return null;
  const now=Date.now(),kickoff=Date.parse(game.kickoff),active=game.status==='in progress in source';
  const target=active?now:kickoff;
  if(game.timeTbd||!Number.isFinite(kickoff)||(active?(now<kickoff||now>kickoff+9*3600000):(target<now||target-now>168*3600000)))return null;
  const venue=game.venue;
  const point=await remote(`nws-point:nfl:${venue.id}`,`https://api.weather.gov/points/${venue.lat},${venue.lon}`,86400000);
  const url=point.data?.properties?.forecastHourly;
  if(point.stale||!/^https:\/\/api\.weather\.gov\/gridpoints\/[A-Z]{3,4}\/\d+,\d+\/forecast\/hourly$/.test(url||''))return null;
  const hourly=await remote(`nws-hourly:nfl:${venue.id}`,url,300000);
  const periods=hourly.data?.properties?.periods;
  if(hourly.stale||!Array.isArray(periods)||periods.length>300)return null;
  const period=periods.find(item=>Date.parse(item.startTime)<=target&&target<Date.parse(item.endTime));
  if(!period)return null;
  const raw={state:'ok',checkedAt:hourly.at,kickoff:game.kickoff,sourceUrl:url,period};
  return active?selectEventHourForecast(game,raw,Date.now()):selectKickoffForecast(game,raw,Date.now());
}
function caseDetail(id,user){
  const item=analystStore.getCaseFor(user,id);
  if(!item)return null;
  item.personScopes=analystStore.getPersonScopesFor(user,id);
  item.briefSnapshots=analystStore.listBriefSnapshotsFor(user,id);
  item.aiDraftEvents=analystStore.listAiDraftEventsFor(user,id);
  item.reviewers=analystStore.listCaseReviewersFor(user,id);
  item.groundZones=analystStore.listGroundZonesFor(user,id);
  if(item.case.subject.type==='voting_site'){
    const current=votingById.get(item.case.subject.id),connector=voting.sources.find(source=>source.id===current?.sourceId||source.id===(item.case.subject.sourceId||item.case.subject.id.split(':')[0]));
    item.sourceDrift=caseVotingDrift(item.case.subject,current,connector);
  }else if(item.case.subject.type==='published_event'){
    const current=publicById.get(item.case.subject.id),connector=published.sources.find(source=>source.id===(item.case.subject.sourceId||current?.sourceId));
    item.sourceDrift=caseEventDrift(item.case.subject,current,connector);
  }
  analystStore.recordCaseRead(user,id,'case.viewed');
  return item;
}
function currentNflGame(caseId,user){
  const detail=analystStore.getCaseFor(user,caseId);
  if(!detail)return null;
  const subject=detail.case.subject,event=publicById.get(subject.id);
  if(subject.type!=='published_event'||subject.sourceId!=='nfl'||caseEventDrift(subject,event,published.sources.find(source=>source.id==='nfl')).status!=='unchanged_since_intake')throw Error('Reconcile NFL event source with case intake before ground-zone use');
  const context=buildNflCaseContext(subject,event,nflSnapshots);
  if(context?.status!=='snapshot_available_unreviewed')throw Error('Fresh, matched NFL schedule snapshot required for ground-zone use');
  const game=nflSchedule.games.find(item=>item.id===subject.id);
  if(!game?.venue?.id||!Number.isFinite(game.venue.lat)||!Number.isFinite(game.venue.lon))throw Error('NFL venue candidate point required');
  return game;
}
async function draftCaseBrief(id,user,includeContext){
  const item=caseDetail(id,user);
  if(!item)return null;
  if(item.case.subject.type!=='published_event')throw Error('Published event case required');
  const event=publicById.get(item.case.subject.id),place=placeById.get(event?.placeId);
  let publicSituation=null;
  if(includeContext&&event&&place&&Number.isFinite(place.lat)&&Number.isFinite(place.lon)){
    const c=await context({id:place.id,lat:place.lat,lon:place.lon});
    publicSituation=buildEventBrief(event,place,{weather:c.weather,earthquakes:c.earthquakes,naturalEvents:c.naturalEvents});
  }
  let nflContext=null;
  if(item.case.subject.sourceId==='nfl')try{
    const game=nflSnapshots.schedule?.games?.find(candidate=>candidate.id===item.case.subject.id);
    let transit=null,transitSchedule=null,transitPredictions=null;
    if(game?.venue?.id==='3738'){
      let scheduleUrl=null;
      try{scheduleUrl=mbtaFoxboroSchedulesUrl(game)}catch{}
      const [response,scheduleResponse,predictionResponse]=await Promise.all([remote('mbta:foxboro',mbtaFoxboroAlertsUrl,300000),scheduleUrl?remote('mbta:foxboro:'+scheduleUrl,scheduleUrl,1800000):Promise.resolve({stale:true}),remote('mbta:foxboro:predictions',mbtaFoxboroPredictionsUrl,120000)]);
      if(!response.stale&&response.data)try{transit=summarizeMbtaFoxboroAlerts(response.data,game,response.at)}catch{transit={state:'failed',checkedAt:Date.now()}}
      else transit={state:'failed',checkedAt:Date.now()};
      if(!scheduleResponse.stale&&scheduleResponse.data)try{transitSchedule=summarizeMbtaFoxboroSchedules(scheduleResponse.data,game,scheduleResponse.at)}catch{transitSchedule={state:'failed',checkedAt:Date.now()}}
      else transitSchedule={state:'failed',checkedAt:Date.now()};
      if(!predictionResponse.stale&&predictionResponse.data)try{transitPredictions=summarizeMbtaFoxboroPredictions(predictionResponse.data,predictionResponse.at)}catch{transitPredictions={state:'failed',checkedAt:Date.now()}}
      else transitPredictions={state:'failed',checkedAt:Date.now()};
    }
    let eonet=await readSiteSnapshot('eonet.json'),conditions=null,soundTransitAlerts=nflSnapshots.soundTransitAlerts,seattleFireAggregate=nflSnapshots.seattleFireAggregate;
    if(game?.id==='nfl:401872992'){
      const check=await remote('sound-transit:alerts',soundTransitAlertsFeed,300000);
      if(!check.stale&&check.data)try{soundTransitAlerts=summarizeSoundTransitAlerts(check.data,check.at)}catch{soundTransitAlerts=null}
      else soundTransitAlerts=null;
    }
    if(game?.venue?.id==='3673'){
      const query=seattleFireAggregateQuery();
      const [count,metadata]=await Promise.all([remote('seattle:fire:count',query.url,300000),remote('seattle:fire:metadata',seattleFireMetadataUrl,300000)]);
      if(!count.stale&&!metadata.stale&&count.data&&metadata.data)try{seattleFireAggregate={...summarizeSeattleFireAggregate(count.data,metadata.data,query,Math.max(count.at,metadata.at)),retrievalMode:'local_server_direct'}}catch{seattleFireAggregate=null}
      else seattleFireAggregate=null;
    }
    if(game){
      const [eonetCheck,usgsCheck]=await Promise.all([remote('eonet',sources.eonet.url,900000),remote('usgs',sources.usgs.url,300000)]);
      if(!eonetCheck.stale&&eonetCheck.data)try{eonet=buildEonetNflSnapshot(eonetCheck.data,nflSnapshots.schedule.games)}catch{eonet=null}
      conditions={at:usgsCheck.at,quakes:usgsCheck.stale?null:usgsCheck.data,quakesError:usgsCheck.stale?usgsCheck.error||'USGS source unavailable':null};
    }
    nflContext=buildNflCaseContext(item.case.subject,event,{...nflSnapshots,eonet,nifc:await readSiteSnapshot('nifc_wildfire.json'),airnow:await readSiteSnapshot('airnow_pm25.json'),hmsSmoke:await readSiteSnapshot('hms_smoke.json'),conditions,septa:await readSiteSnapshot('septa_b_alerts.json'),soundTransitAlerts,seattleFireAggregate,transit,transitSchedule,transitPredictions});
  }catch{nflContext={status:'unavailable',reason:'NFL source snapshots could not be assembled.',evidence:null}}
  const trace=analystStore.recordBriefRequest(user,id);
  const brief=buildInternalCaseBrief(item,{generatedAt:trace.generatedAt,generatedBy:user.id,auditHead:trace.auditHead,publicSituation,nflContext});
  brief.changesSincePreviousBrief=compareBriefSnapshots(analystStore.getLatestBriefSnapshotFor(user,id),brief);
  return brief;
}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/meta')return send(res,200,{count:venues.length,retrievedAt:snapshot.retrievedAt,coverageNote:snapshot.coverageNote,source:snapshot.source,types:snapshot.queryClasses.map(x=>x[0]),feeds:sources,publishedEvents:{count:published.events.length,placeCount:published.places.length,retrievedAt:published.retrievedAt,sources:published.sources,coverageNote:published.coverageNote},voting:{count:voting.locations.length,retrievedAt:voting.retrievedAt,coverageNote:voting.coverageNote,sources:voting.sources},dns:{hostCount:dnsSnapshot.hosts.length,observedAt:dnsSnapshot.observedAt,caution:dnsSnapshot.caution}});if(u.pathname==='/api/operators/me'&&req.method==='GET'){const user=operator(req,res);return user&&send(res,200,{operator:user,audit:analystStore.auditSummary()})}if(u.pathname==='/api/events'&&req.method==='GET'){const user=operator(req,res);return user&&send(res,200,{items:analystStore.listEvents()})}
if(u.pathname==='/api/cases'&&req.method==='GET'){const user=operator(req,res);if(!user)return;const items=analystStore.listCasesFor(user);analystStore.recordCaseList(user,items.map(item=>item.id));return send(res,200,{items,caution:'Internal analyst cases only; no protective notification or external dissemination'})}
if(u.pathname==='/api/cases'&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const body=await readBody(req);let subject=null;if(body.subjectType==='published_event'){const e=publicById.get(body.subjectId);if(e)subject={type:'published_event',id:e.id,sourceId:e.sourceId,title:e.title,sourceUrl:e.sourceUrl,retrievedAt:e.retrievedAt,startsAtLocal:e.startsAtLocal,placeId:e.placeId||null,sourceStatus:e.status,connectorStatus:published.sources.find(s=>s.id===e.sourceId)?.status||'unknown',operationalSnapshot:projectEvent(e)}}else if(body.subjectType==='voting_site'){const v=votingById.get(body.subjectId);if(v)subject={type:'voting_site',id:v.id,sourceId:v.sourceId,title:v.name,sourceUrl:v.sourceRecordUrl||v.sourceUrl,retrievedAt:v.retrievedAt,sourceDataStatus:v.sourceDataStatus,connectorStatus:voting.sources.find(s=>s.id===v.sourceId)?.status||'unknown',operationalSnapshot:projectVotingSite(v)}}if(!subject)return send(res,400,{error:'Known published event or voting site required'});try{return send(res,201,analystStore.createCase(user,subject,body.purpose,body.authority,body.openingRationale))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/reviewers')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/reviewers'.length));const body=await readBody(req);try{return send(res,201,analystStore.assignCaseReviewer(user,id,body.reviewerId,body.rationale))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/case-reviewers/')&&u.pathname.endsWith('/revoke')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/case-reviewers/'.length,-'/revoke'.length));const body=await readBody(req);try{return send(res,200,analystStore.revokeCaseReviewer(user,id,body.rationale))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/ground-zones/screen')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/ground-zones/screen'.length));const body=await readBody(req);try{const game=currentNflGame(id,user);if(!game)return send(res,404,{error:'Case not found'});const zones=analystStore.listGroundZonesFor(user,id);const results=screenControlledGroundZones(zones,game,body);analystStore.recordCaseRead(user,id,'ground_zone.screened');return send(res,200,{eventId:game.id,venueId:game.venue.id,results,interpretation:'Local planning relation only; no observation is persisted, no alert is generated, and no field boundary is verified.'})}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/ground-zones')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/ground-zones'.length));const body=await readBody(req);try{const game=currentNflGame(id,user);if(!game)return send(res,404,{error:'Case not found'});return send(res,201,analystStore.createGroundZone(user,id,normalizeGroundZone(body,game)))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/ground-zones/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/ground-zones/'.length,-'/review'.length));const body=await readBody(req);try{const zone=analystStore.getGroundZoneFor(user,id);if(!zone)return send(res,404,{error:'Ground zone not found'});const game=currentNflGame(zone.caseId,user);if(game?.id!==zone.eventId||game.venue.id!==zone.venueId)throw Error('Event or venue changed; ground zone must be resubmitted');return send(res,201,analystStore.reviewGroundZone(user,id,body.decision,body.rationale,body.verificationReference))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/ground-zones/')&&u.pathname.endsWith('/revoke')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/ground-zones/'.length,-'/revoke'.length));const body=await readBody(req);try{return send(res,200,analystStore.revokeGroundZone(user,id,body.rationale))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/assessments')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/assessments'.length));const body=await readBody(req);try{return send(res,201,analystStore.createAssessment(user,id,body))}catch(error){return send(res,error.message==='Case not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/assessments/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/assessments/'.length,-'/review'.length));const body=await readBody(req);try{return send(res,201,analystStore.reviewAssessment(user,id,body.decision,body.rationale))}catch(error){return send(res,error.message==='Assessment not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/person-scopes')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/person-scopes'.length));const body=await readBody(req);try{return send(res,201,analystStore.requestPersonScope(user,id,body))}catch(error){return send(res,error.message==='Case not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/person-scopes/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/person-scopes/'.length,-'/review'.length));const body=await readBody(req);try{return send(res,201,analystStore.reviewPersonScope(user,id,body.decision,body.rationale))}catch(error){return send(res,error.message==='Scope not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/person-scopes/')&&u.pathname.endsWith('/people')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/person-scopes/'.length,-'/people'.length));const body=await readBody(req);try{return send(res,201,analystStore.createProtectedPerson(user,id,body))}catch(error){return send(res,error.message==='Scope not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/protected-people/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/protected-people/'.length,-'/review'.length));const body=await readBody(req);try{return send(res,201,analystStore.reviewProtectedPerson(user,id,body.decision,body.rationale))}catch(error){return send(res,error.message==='Person not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/brief')&&req.method==='GET'){const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/brief'.length));try{const brief=await draftCaseBrief(id,user,u.searchParams.get('context')!=='none');return brief?send(res,200,brief):send(res,404,{error:'Case not found'})}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/ai-draft')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/ai-draft'.length));try{const brief=await draftCaseBrief(id,user,false);if(!brief)return send(res,404,{error:'Case not found'});const game=nflSchedule?.games?.find(item=>item.id===brief.nflContext?.evidence?.event?.id);const [directGame,forecastContext]=game?await Promise.all([fetchSelectedGame(game),selectedNflForecast(game)]):[null,null];const packet=buildLocalAiPacket(brief,{directGame,forecastContext}),requestId=randomUUID(),packetHash=localAiDraftHash(packet);analystStore.recordAiDraftEvent(user,id,{requestId,model:LOCAL_MODEL,packetHash,stage:'requested'});let result;try{result=await generateLocalAiDraft(packet)}catch(error){analystStore.recordAiDraftEvent(user,id,{requestId,model:LOCAL_MODEL,packetHash,stage:'failed',errorCode:'generation_failed'});throw error}const draftHash=localAiDraftHash(result.draft),receipt=analystStore.recordAiDraftEvent(user,id,{requestId,model:LOCAL_MODEL,packetHash,stage:'succeeded',draftHash});return send(res,200,{...result,draftSha256:draftHash,receiptId:receipt.id,receiptAuditHead:receipt.auditHead})}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/brief-snapshots')&&req.method==='GET'){const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/brief-snapshots'.length)),items=analystStore.listBriefSnapshotsFor(user,id);if(!items)return send(res,404,{error:'Case not found'});analystStore.recordCaseRead(user,id,'brief_snapshot.listed');return send(res,200,{items})}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/brief-snapshots')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/brief-snapshots'.length));try{const brief=await draftCaseBrief(id,user,u.searchParams.get('context')!=='none');if(!brief)return send(res,404,{error:'Case not found'});return send(res,201,analystStore.saveBriefSnapshot(user,id,brief))}catch(error){return send(res,400,{error:error.message})}}
if(u.pathname.startsWith('/api/brief-snapshots/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/brief-snapshots/'.length,-'/review'.length));const body=await readBody(req);try{return send(res,201,analystStore.reviewBriefSnapshot(user,id,body.decision,body.rationale))}catch(error){return send(res,error.message==='Brief snapshot not found'?404:400,{error:error.message})}}
if(u.pathname.startsWith('/api/brief-snapshots/')&&req.method==='GET'){const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/brief-snapshots/'.length)),item=analystStore.getBriefSnapshotFor(user,id);if(!item)return send(res,404,{error:'Brief snapshot not found'});analystStore.recordCaseRead(user,item.caseId,'brief_snapshot.viewed',id);return send(res,200,item)}
if(u.pathname.startsWith('/api/cases/')&&u.pathname.endsWith('/access-log')&&req.method==='GET'){const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length,-'/access-log'.length)),items=analystStore.listCaseAccessFor(user,id);return items?send(res,200,{items,limit:500}):send(res,404,{error:'Case not found'})}
if(u.pathname.startsWith('/api/cases/')&&req.method==='GET'){const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/cases/'.length)),item=caseDetail(id,user);return item?send(res,200,item):send(res,404,{error:'Case not found'})}
if(u.pathname==='/api/changes'){const source=u.searchParams.get('source')||'',kind=u.searchParams.get('kind')||'',limit=Math.min(500,Math.max(1,Number(u.searchParams.get('limit')||100)));const items=eventChanges.filter(x=>(!source||x.sourceId===source)&&(!kind||x.kind===kind));return send(res,200,{total:items.length,items:items.slice(0,limit),snapshots:[{name:'municipal',generatedAt:municipal.changeSet?.generatedAt||null,comparedTo:municipal.changeSet?.comparedTo||null,retainedSources:municipal.changeSet?.retainedSources||[]},{name:'sports',generatedAt:sports.changeSet?.generatedAt||null,comparedTo:sports.changeSet?.comparedTo||null,retainedSources:sports.changeSet?.retainedSources||[]}],caution:'Latest refresh comparison only. Missing from feed does not establish cancellation.'})}
if(u.pathname==='/api/voting-history'){const limit=Math.min(50,Math.max(1,Number(u.searchParams.get('limit')||10)));return send(res,200,{total:votingHistory.length,items:votingHistory.slice(-limit).reverse(),verified:true,caution:'Local content-addressed archives; backfilled runs were archived after their original refresh. Filesystem access can still alter or delete history.'})}
if(u.pathname==='/api/voting-changes'){const source=u.searchParams.get('source')||'',kind=u.searchParams.get('kind')||'',limit=Math.min(500,Math.max(1,Number(u.searchParams.get('limit')||100)));const all=voting.changeSet?.items||[],items=all.filter(change=>(!source||change.sourceId===source)&&(!kind||change.kind===kind));return send(res,200,{total:items.length,items:items.slice(0,limit),generatedAt:voting.changeSet?.generatedAt||null,comparedTo:voting.changeSet?.comparedTo||null,retainedSources:voting.changeSet?.retainedSources||[],caution:'Latest comparison only. Missing from a successful feed is not verified closure or cancellation.'})}
if(u.pathname==='/api/voting-locations'){const q=(u.searchParams.get('q')||'').trim().toLowerCase(),type=u.searchParams.get('type')||'',state=u.searchParams.get('state')||'',offset=Math.max(0,Number(u.searchParams.get('offset')||0)),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)));const items=voting.locations.filter(v=>(!type||v.type===type)&&(!state||v.jurisdiction===state)&&(!q||[v.name,v.city,v.county,v.street,v.postal].some(x=>x?.toLowerCase().includes(q))));const sourceStatus=new Map(voting.sources.map(source=>[source.id,source.status]));return send(res,200,{total:items.length,staleCount:items.filter(site=>sourceStatus.get(site.sourceId)!=='ok').length,items:items.slice(offset,offset+limit).map(site=>({...site,connectorStatus:sourceStatus.get(site.sourceId)||'unknown'})),retrievedAt:voting.retrievedAt,coverageNote:voting.coverageNote})}
if(u.pathname.startsWith('/api/voting-location/')){const id=decodeURIComponent(u.pathname.slice('/api/voting-location/'.length));const v=votingById.get(id);if(!v)return send(res,404,{error:'Voting location not found'});const c=Number.isFinite(v.lat)&&Number.isFinite(v.lon)?await context({id:v.id,lat:v.lat,lon:v.lon}):null;return send(res,200,{location:v,source:voting.sources.find(source=>source.id===v.sourceId)||null,conditions:c?{weather:c.weather,earthquakes:c.earthquakes,naturalEvents:c.naturalEvents}:null})}
if(u.pathname==='/api/events'&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const e=await readBody(req);if(typeof e.title!=='string'||!e.title.trim()||e.title.length>200||!byId.has(e.venueId)||!e.startsAt||!e.sourceUrl)return send(res,400,{error:'Valid title, venueId, startsAt and sourceUrl required'});let parsed;try{parsed=new URL(e.sourceUrl)}catch{}if(parsed?.protocol!=='https:'||Number.isNaN(Date.parse(e.startsAt))||(e.endsAt&&Number.isNaN(Date.parse(e.endsAt)))||(e.endsAt&&Date.parse(e.endsAt)<Date.parse(e.startsAt)))return send(res,400,{error:'Invalid source URL or schedule'});const attendance=e.expectedAttendance===''||e.expectedAttendance==null?null:Number(e.expectedAttendance);if(attendance!==null&&(!Number.isSafeInteger(attendance)||attendance<0))return send(res,400,{error:'Invalid expected attendance'});const event=analystStore.createEvent(user,{title:e.title.trim(),venueId:e.venueId,startsAt:e.startsAt,endsAt:e.endsAt||null,organizer:String(e.organizer||'').slice(0,200),expectedAttendance:attendance,sourceUrl:parsed.toString(),owner:user.name});return send(res,201,event)}
if(u.pathname.startsWith('/api/events/')&&u.pathname.endsWith('/review')&&req.method==='POST'){if(!sameOrigin(req,res))return;const user=operator(req,res);if(!user)return;const id=decodeURIComponent(u.pathname.slice('/api/events/'.length,-'/review'.length));const body=await readBody(req);try{return send(res,201,analystStore.reviewEvent(user,id,body.decision,body.rationale))}catch(error){return send(res,error.message==='Event not found'?404:400,{error:error.message})}}
if(u.pathname==='/api/public-events'){const q=(u.searchParams.get('q')||'').trim().toLowerCase(),source=u.searchParams.get('source')||'',offset=Math.max(0,Number(u.searchParams.get('offset')||0)),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50))),now=Date.now();const items=published.events.filter(e=>(!source||e.sourceId===source)&&(!q||[e.title,e.sourcePlace.name,e.category,e.organizer].some(x=>x?.toLowerCase().includes(q)))).sort((a,b)=>{if(source!=='nfl')return a.startsAtLocal.localeCompare(b.startsAtLocal);const at=Date.parse(a.startsAtLocal),bt=Date.parse(b.startsAtLocal),af=at>=now,bf=bt>=now;return af!==bf?af?-1:1:af?at-bt:bt-at});return send(res,200,{total:items.length,items:items.slice(offset,offset+limit),retrievedAt:published.retrievedAt})}
if(u.pathname.startsWith('/api/public-event/')){const id=decodeURIComponent(u.pathname.slice('/api/public-event/'.length));const e=publicById.get(id);if(!e)return send(res,404,{error:'Event not found'});const place=placeById.get(e.placeId)||null;let conditions=null;if(place&&Number.isFinite(place.lat)&&Number.isFinite(place.lon)){const c=await context({id:place.id,lat:place.lat,lon:place.lon});conditions={weather:c.weather,earthquakes:c.earthquakes,naturalEvents:c.naturalEvents}}const forecast=await kickoffForecast(e,place);return send(res,200,{event:e,place,conditions,forecast,brief:buildEventBrief(e,place,conditions)})}
if(u.pathname==='/api/map'){const step=Math.max(1,Math.ceil(venues.length/1000));return send(res,200,{total:venues.length,items:venues.filter((_,i)=>i%step===0)})}
if(u.pathname==='/api/venues'){const q=(u.searchParams.get('q')||'').trim().toLowerCase(),type=u.searchParams.get('type')||'',limit=Math.min(500,Math.max(1,Number(u.searchParams.get('limit')||100))),offset=Math.max(0,Number(u.searchParams.get('offset')||0));let items=venues.filter(v=>(!type||v.type===type)&&(!q||[v.name,v.city,v.region,v.street,v.id].some(x=>x?.toLowerCase().includes(q))));return send(res,200,{total:items.length,items:items.slice(offset,offset+limit)})}if(u.pathname.startsWith('/api/venue/')){const id=u.pathname.slice('/api/venue/'.length);const v=byId.get(id);return v?send(res,200,await context(v)):send(res,404,{error:'Venue not found'})}if(u.pathname==='/api/health')return send(res,200,{status:'ok',venueCount:venues.length});let filename=u.pathname==='/'?'index.html':u.pathname.replace(/^\//,'');if(filename.includes('..'))return send(res,400,{error:'Bad path'});const full=path.join(root,'public',filename);const body=await fs.readFile(full);res.writeHead(200,{...securityHeaders,'Content-Type':types[path.extname(full)]||'application/octet-stream','Cache-Control':'no-store'});res.end(body)}catch(e){if(e.code==='ENOENT')return send(res,404,{error:'Not found'});if(e.statusCode)return send(res,e.statusCode,{error:e.message});console.error(e);send(res,500,{error:'Internal server error'})}}).listen(port,'127.0.0.1',()=>console.log(`Event Atlas http://127.0.0.1:${port}`));
