import fs from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const publicEvents=JSON.parse(await fs.readFile(path.join(root,'data/public_events.json'),'utf8'));
const voting=JSON.parse(await fs.readFile(path.join(root,'data/voting_locations.json'),'utf8'));
const selected=[['nyc-parks:2158498','concert'],['nyc-parks:2153686','concert'],['nyc-parks:2190781','concert'],['nyc-parks:2255018','festival'],['nyc-parks:2230956','festival']];
const events=[];
for(const [id,eventType] of selected){const event=publicEvents.events.find(e=>e.id===id);if(!event)continue;const p=event.sourcePlace;if(!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lon))continue;
 events.push({id,eventType,title:event.title,kickoff:event.startsAtLocal+'-04:00',endsAt:event.endsAtLocal+'-04:00',status:'Published schedule',sourceUrl:event.sourceUrl,sourceDataset:event.sourceDataset,sourceRetrievedAt:event.retrievedAt,description:event.description,organizer:event.organizer,venue:{id:event.placeId,name:p.name,address:p.address+', New York, NY, USA',lat:p.lat,lon:p.lon,coordinateStatus:'Publisher location'},scenarios:eventType==='concert'?[{priority:'medium',title:'Blocked audience exit',observation:'A fictional steward report describes a temporary vendor queue across an audience exit.',uncertainty:'The remaining exit capacity and duration have not been verified.',decision:'Have the event supervisor verify the route and relocate the queue if it obstructs the approved exit.',owner:'Event safety supervisor',escalate:'The obstruction persists or safe exit capacity is reduced.',close:'The exit is verified clear.'}]:[{priority:'low',title:'Separated child at a family event',observation:'A fictional visitor reports a child separated from their group.',uncertainty:'The child’s location and identity are unverified.',decision:'Activate the event’s reunification procedure without publicly broadcasting identifying details.',owner:'Guest-services lead',escalate:'A corroborated immediate safety concern or a prolonged unresolved separation.',close:'Authorized reunification is confirmed.'}]});}
for(const sourceId of ['dc-early','dc-election-day'])for(const place of voting.locations.filter(p=>p.sourceId===sourceId).slice(0,2)){
 const early=sourceId==='dc-early';events.push({id:'voting:'+place.id,eventType:'voting',title:(early?'Early voting':'Election Day voting')+' — '+place.name,kickoff:early?'2026-10-26T08:30:00-04:00':'2026-11-03T07:00:00-05:00',endsAt:early?'2026-11-01T19:00:00-05:00':'2026-11-03T20:00:00-05:00',status:'Published site record',sourceUrl:place.sourceRecordUrl,sourceDataset:place.sourceUrl,sourceRetrievedAt:place.retrievedAt,description:'Published voting location. Confirm current hours, accessibility and voter eligibility with the election authority.',organizer:'District of Columbia Board of Elections',datesOpen:place.datesOpen,hours:place.hours,votingSpace:place.votingSpace,accessibility:place.accessibility||'Not supplied',venue:{id:place.id,name:place.name,address:place.street+', Washington, DC, USA',lat:place.lat,lon:place.lon,coordinateStatus:'Official GIS location'},scenarios:[{priority:early?'medium':'high',title:early?'Accessible entrance obstruction':'Reported threat toward election workers',observation:early?'A fictional site manager reports a delivery blocking the accessible entrance.':'A fictional reporting desk receives a direct threat naming the voting site and its workers.',uncertainty:early?'Whether another approved accessible entrance is available is unknown.':'Sender identity, capability, location and credibility remain unverified; no voter is implicated.',decision:early?'Have the site manager verify accessible entry and coordinate removal of the obstruction.':'Have the designated election-security lead promptly assess the report, preserve evidence and consider proportionate worker protection under the site response plan.',owner:early?'Voting-site manager':'Election-security lead',escalate:early?'Accessible voter entry cannot be maintained.':'Corroboration establishes capability, site access or immediate danger.',close:early?'Approved accessible entry is verified restored.':'A responsible reviewer documents a supported resolution.'}]});}
await fs.writeFile(path.join(root,'site/event_examples.json'),JSON.stringify({builtAt:new Date().toISOString(),coverage:'Curated examples from existing public snapshots; not comprehensive event or voting-location coverage.',events},null,2)+'\n');
console.log(`Built ${events.length} additional event examples`);
