import fs from 'node:fs/promises';
import dns from 'node:dns/promises';
import {domainToASCII} from 'node:url';
const snapshot=JSON.parse(await fs.readFile('data/venues.json','utf8'));
const hosts=new Map();
function public4(ip){const x=ip.split('.').map(Number);if(x.length!==4||x.some(n=>!Number.isInteger(n)||n<0||n>255))return false;const [a,b]=x;return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19)||a===192&&b===0||a===192&&b===2||a===198&&b===51||a===203&&b===0)}
for(const v of snapshot.venues){if(!v.website)continue;try{const u=new URL(v.website);if(!['http:','https:'].includes(u.protocol))continue;const host=domainToASCII(u.hostname.toLowerCase());if(!host||!host.includes('.')||host.endsWith('.local'))continue;let h=hosts.get(host);if(!h){h={hostname:host,venueIds:[],websiteSources:[]};hosts.set(host,h)}h.venueIds.push(v.id);h.websiteSources.push(v.source)}catch{}}
const entries=[...hosts.values()];let next=0;const results=[];
async function worker(){for(;;){const i=next++;if(i>=entries.length)return;const h=entries[i];let addresses=[],cname=[],error=null;try{addresses=(await Promise.race([dns.resolve4(h.hostname),new Promise((_,r)=>setTimeout(()=>r(Error('DNS timeout')),4000))])).filter(public4)}catch(e){error=String(e.code||e.message)}try{cname=await Promise.race([dns.resolveCname(h.hostname),new Promise((_,r)=>setTimeout(()=>r(Error('DNS timeout')),4000))])}catch{}results.push({...h,addresses,cname,observedAt:new Date().toISOString(),error,attribution:'Website hostname DNS observation only; IP ownership and venue system use unverified'})}}
await Promise.all(Array.from({length:20},worker));results.sort((a,b)=>a.hostname.localeCompare(b.hostname));const out={source:'DNS A and CNAME lookup of Wikidata website hostnames',venueSnapshotAt:snapshot.retrievedAt,observedAt:new Date().toISOString(),caution:'Addresses are linked to published website hostnames, not attributed to venue-owned systems. CDNs, shared hosting and third-party sites are common. No port scanning performed.',hosts:results};await fs.writeFile('data/dns_observations.json',JSON.stringify(out));console.log('hosts',results.length,'with public A',results.filter(x=>x.addresses.length).length,'unique public A',new Set(results.flatMap(x=>x.addresses)).size);
