import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {saveReconciledEventSnapshot} from '../lib/event_snapshot.mjs';
const venueSnapshot=JSON.parse(await fs.readFile('data/venues.json','utf8'));
const venues=venueSnapshot.venues;
const now=new Date();const from=now.toISOString().slice(0,10);
const sources=[
 {id:'nyc-parks',name:'NYC Parks Public Events — Upcoming 14 Days',dataset:'https://data.cityofnewyork.us/City-Government/NYC-Parks-Public-Events-Upcoming-14-Days/w3wp-dpdi',api:'https://data.cityofnewyork.us/resource/w3wp-dpdi.json',tz:'America/New_York',where:`starttime >= '${from}'`},
 {id:'chicago-library',name:'Chicago Public Library Events',dataset:'https://data.cityofchicago.org/Events/Chicago-Public-Library-Events/vsdy-d8k7',api:'https://data.cityofchicago.org/resource/vsdy-d8k7.json',tz:'America/Chicago',where:`start >= '${from}'`},
 {id:'chicago-special',name:'City of Chicago Special Events',dataset:'https://data.cityofchicago.org/Events/Special-Events/xgse-8eg7',api:'https://data.cityofchicago.org/resource/xgse-8eg7.json',tz:'America/Chicago',where:`date >= '${from}'`}
];
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&#8217;|&#039;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const https=s=>typeof s==='string'&&/^https?:\/\//.test(s)?s.replace(/^http:/,'https:'):null;
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const dist=(a,b,c,d)=>6371*Math.hypot((d-b)*Math.PI/180*Math.cos((a+c)*Math.PI/360),(c-a)*Math.PI/180);
function match(name,lat,lon){if(!name||!Number.isFinite(lat)||!Number.isFinite(lon))return null;const n=norm(name);const hits=venues.filter(v=>norm(v.name)===n&&dist(lat,lon,v.lat,v.lon)<.5);return hits.length===1?hits[0].id:null}
function event(source,row){let title,start,end,place,address,category,url,lat,lon,id,description,cancelled=false;
 if(source.id==='nyc-parks'){title=row.title;start=row.starttime;end=row.endtime;place=row.parknames||row.location;address=row.location;category=row.categories;url=row.link?.url;id=row.guid;description=row.description;const p=(row.coordinates||'').split(',').map(Number);lat=p[0];lon=p[1]}
 else if(source.id==='chicago-library'){title=row.title;start=row.start;end=row.end;place=row.location_name;address=[row.location_address,row.location_zip].filter(Boolean).join(', ');category=row.event_types;url=row.event_page?.url;id=row.event_id;description=row.description;cancelled=!!row.cancelled;lon=row.location?.coordinates?.[0];lat=row.location?.coordinates?.[1]}
 else {title=row.event_details;start=row.date?.slice(0,10)+(row.start_time?' '+row.start_time:'');end=null;place=row.venue;address=row.venue_address;category=row.event_type;url=source.dataset;id=crypto.createHash('sha256').update(JSON.stringify(row)).digest('hex').slice(0,16);description=null;lon=row.location?.coordinates?.[0];lat=row.location?.coordinates?.[1]}
 if(!title||!start)return null;cancelled=cancelled||/^CANCEL(?:L)?ED[: -]/i.test(clean(title));const sourcePlace={name:clean(place)||null,address:clean(address)||null,lat:Number.isFinite(+lat)?+lat:null,lon:Number.isFinite(+lon)?+lon:null};
 return {id:`${source.id}:${id||crypto.createHash('sha256').update(title+start+place).digest('hex').slice(0,16)}`,title:clean(title),startsAtLocal:start,endsAtLocal:end||null,timeZone:source.tz,sourceId:source.id,sourceUrl:https(url)||source.dataset,sourceDataset:source.dataset,sourcePlace,venueId:match(sourcePlace.name,sourcePlace.lat,sourcePlace.lon),category:clean(category)||null,description:clean(description).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[email omitted]').replace(/(?:\+?1[-. ]?)?\(?\d{3}\)?[-. ]?\d{3}[-. ]?\d{4}/g,'[phone omitted]').slice(0,800)||null,organizer:source.id==='nyc-parks'?'NYC Parks':source.id==='chicago-library'?'Chicago Public Library':'City of Chicago',status:cancelled?'cancelled in source':'published-source; unreviewed',retrievedAt:new Date().toISOString()};
}
async function fetchPage(source,offset){const u=new URL(source.api);u.searchParams.set('$limit','1000');u.searchParams.set('$offset',String(offset));u.searchParams.set('$where',source.where);const r=await fetch(u,{headers:{'User-Agent':'EventAtlas/0.2 (public event source evaluation)'},signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data))throw Error('Unexpected source schema');return data}
const all=[];const results=[];for(const source of sources){try{let count=0;for(let offset=0;offset<10000;offset+=1000){const rows=await fetchPage(source,offset);for(const row of rows){const x=event(source,row);if(x){all.push(x);count++}}if(rows.length<1000)break}results.push({id:source.id,name:source.name,dataset:source.dataset,api:source.api,status:'ok',records:count,retrievedAt:new Date().toISOString()});console.log(source.id,count)}catch(e){results.push({id:source.id,name:source.name,dataset:source.dataset,api:source.api,status:'failed',error:String(e),retrievedAt:new Date().toISOString()});console.error(source.id,String(e))}}
const unique=new Map(all.map(x=>[x.id,x]));const places=new Map();for(const e of unique.values()){const p=e.sourcePlace;if(!p.name&&!Number.isFinite(p.lat))continue;const key=[norm(p.name),Number.isFinite(p.lat)?p.lat.toFixed(4):'',Number.isFinite(p.lon)?p.lon.toFixed(4):''].join('|');const id='place:'+crypto.createHash('sha256').update(key).digest('hex').slice(0,16);e.placeId=id;if(!places.has(id))places.set(id,{id,name:p.name,address:p.address,lat:p.lat,lon:p.lon,sourceIds:[e.sourceId],venueCandidateId:e.venueId});else if(!places.get(id).sourceIds.includes(e.sourceId))places.get(id).sourceIds.push(e.sourceId)}const candidate={retrievedAt:new Date().toISOString(),fromDate:from,coverageNote:'Selected public municipal calendars only; entries may change or be cancelled. Events link to source-derived places; Wikidata venue links require exact name and proximity and remain unreviewed.',sources:results,places:[...places.values()],events:[...unique.values()]};const out=await saveReconciledEventSnapshot('data/public_events.json',candidate);console.log('total',out.events.length,'venue linked',out.events.filter(x=>x.venueId).length,'changes',out.changeSet.items.length);
