import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ny='https://services6.arcgis.com/EbVsqZ18sv1kVJ3k/arcgis/rest/services/NYS_Elections_Districts_and_Polling_Locations/FeatureServer';
const dc='https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Government_Operations/MapServer';
const md='https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/2026_Maryland_General_Election_Voting_Sites_WFL1/FeatureServer';
const layers=[
  {id:'ny-early-outside-nyc',base:ny,layer:0,name:'New York State early voting sites, outside NYC',type:'early_vote_center',jurisdiction:'NY',status:'June 2026 location candidate; verify for each election'},
  {id:'ny-early-nyc',base:ny,layer:1,name:'New York State early voting sites, NYC',type:'early_vote_center',jurisdiction:'NY',status:'June 2026 location candidate; verify for each election'},
  {id:'ny-election-day-outside-nyc',base:ny,layer:2,name:'New York State Election Day sites, outside NYC',type:'election_day_polling_place',jurisdiction:'NY',status:'June 2026 location candidate; verify for each election'},
  {id:'ny-election-day-nyc',base:ny,layer:3,name:'New York State Election Day sites, NYC',type:'election_day_polling_place',jurisdiction:'NY',status:'June 2026 location candidate; verify for each election'},
  {id:'dc-election-day',base:dc,layer:9,name:'DC Election Day vote centers',type:'election_day_vote_center',jurisdiction:'DC',status:'2026 general election source record; verify current status'},
  {id:'dc-early',base:dc,layer:10,name:'DC early vote centers',type:'early_vote_center',jurisdiction:'DC',status:'2026 general election source record; verify current status'},
  {id:'dc-drop-box',base:dc,layer:8,name:'DC mail-ballot drop boxes',type:'ballot_drop_box',jurisdiction:'DC',status:'2026 general election source record; verify current status'},
  {id:'md-election-day',base:md,layer:1,name:'Maryland 2026 general-election polling places',type:'election_day_polling_place',jurisdiction:'MD',status:'2026 general-election GIS candidate; verify with local board before action'}
];
async function json(url,maxAttempts=4){let last;for(let attempt=0;attempt<maxAttempts;attempt++){try{const r=await fetch(url,{headers:{'User-Agent':'EventAtlas/0.4 (local public-data evaluation)','Accept':'application/json'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`${r.status} ${url}`);const data=await r.json();if(data.error)throw Error(`${url}: ${JSON.stringify(data.error)}`);return data}catch(error){last=error;if(attempt<maxAttempts-1)await new Promise(resolve=>setTimeout(resolve,1000*2**attempt))}}throw last}
const clean=v=>typeof v==='string'?v.trim():v==null?'':String(v);
function normalize(source,f,retrievedAt){const p=f.properties||{},[lon,lat]=f.geometry?.coordinates||[];if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<24||lat>50||lon< -126||lon> -66)return null;const isNY=source.jurisdiction==='NY',isMD=source.jurisdiction==='MD',recordId=p.OBJECTID??p.ObjectID;const name=clean(p.USER_Poll_Site_Name||p.USER_Poll_Site||p.USER_Polling_Place_Name||p.USER_Polling_Place||p.LOCATION);if(!name||recordId==null)return null;const address=clean(p.USER_Poll_Site_Address||p.USER_Address1||p.USER_Polling_Place_Address_1||p.USER_Address||p.ADDRESS);const city=clean(p.USER_City||p.City||(isMD?'':'Washington'));return {id:`${source.id}:${recordId}`,sourceId:source.id,sourceRecordId:recordId,name,type:source.type,jurisdiction:source.jurisdiction,county:clean(p.USER_County||p.USER_CountyName),city,street:address,addressLine2:clean(p.USER_Address2||p.USER_Polling_Place_Address_2),postal:clean(p.USER_ZipCode||p.USER_Zip||p.MAR_ZIPCODE||p.ZIP),lat,lon,precinct:clean(p.USER_Precinct_s_)||null,ward:clean(p.MAR_WARD),status:clean(p.STATUS)||'Not supplied',datesOpen:clean(p.DATES_OPEN),hours:clean(p.TIME_OPEN),votingSpace:clean(p.VOTING_SPACE),accessibility:clean(p.ACCESSIBILITY),sourceUrl:`${source.base}/${source.layer}`,sourceRecordUrl:`${source.base}/${source.layer}/query?where=${isMD?'ObjectID':'OBJECTID'}%3D${recordId}&outFields=*&returnGeometry=true&f=geojson`,sourceDataStatus:source.status,retrievedAt,sourceEditedAt:isNY?null:p.LAST_EDITED_DATE?new Date(p.LAST_EDITED_DATE).toISOString():null};}
async function rangeFeatures(base,idField,start,end){const q=new URLSearchParams({where:`${idField} >= ${start} AND ${idField} < ${end}`,outFields:'*',returnGeometry:'true',outSR:'4326',f:'geojson'});try{const page=await json(`${base}/query?${q}`,2);if(!Array.isArray(page.features))throw Error(`Missing features for ${start}–${end}`);return page.features}catch(error){if(end-start<=25)throw error;const middle=start+Math.floor((end-start)/2);const first=await rangeFeatures(base,idField,start,middle);const second=await rangeFeatures(base,idField,middle,end);return [...first,...second]}}
async function load(source,retrievedAt){const base=`${source.base}/${source.layer}`;const meta=await json(`${base}?f=json`);const ids=await json(`${base}/query?where=1%3D1&returnIdsOnly=true&f=json`);if(!Array.isArray(ids.objectIds)||!ids.objectIds.length)throw Error(`${source.id}: empty/invalid ID list`);let items=[];const idField=meta.objectIdField||'OBJECTID';for(let start=Math.min(...ids.objectIds);start<=Math.max(...ids.objectIds);start+=200)items.push(...await rangeFeatures(base,idField,start,start+200));if(items.length!==ids.objectIds.length)throw Error(`${source.id}: expected ${ids.objectIds.length}, received ${items.length}`);const locations=items.map(f=>normalize(source,f,retrievedAt)).filter(Boolean);if(locations.length!==items.length)throw Error(`${source.id}: ${items.length-locations.length} records failed normalization`);return {source:{id:source.id,name:source.name,dataset:base,records:locations.length,reportedCount:ids.objectIds.length,retrievedAt,dataEditedAt:meta.editingInfo?.dataLastEditDate?new Date(meta.editingInfo.dataLastEditDate).toISOString():null,coverageNote:source.status,status:'ok'},locations}}
const retrievedAt=new Date().toISOString();const file=path.join(root,'data/voting_locations.json');const previous=JSON.parse(await fs.readFile(file,'utf8').catch(error=>{if(error.code==='ENOENT')return 'null';throw error}));const results=[];for(const layer of layers){try{const result=await load(layer,retrievedAt);results.push(result);console.log(`${layer.id}: ${result.locations.length}`)}catch(error){const locations=previous?.locations.filter(x=>x.sourceId===layer.id)||[];results.push({source:{id:layer.id,name:layer.name,dataset:`${layer.base}/${layer.layer}`,records:locations.length,retrievedAt,lastSuccessfulAt:(()=>{const prior=previous?.sources.find(x=>x.id===layer.id);return prior?.status==='ok'?prior.retrievedAt:locations[0]?.retrievedAt||prior?.lastSuccessfulAt||null})(),coverageNote:layer.status,status:locations.length?'stale_retained':'error',error:String(error.message)},locations});console.error(`${layer.id}: ${error.message}; retained ${locations.length} prior records`)}}
if(!results.some(x=>x.source.status==='ok'))throw Error('No voting GIS source succeeded; previous snapshot preserved');
const managedIds=new Set(layers.map(layer=>layer.id));
const retainedSources=(previous?.sources||[]).filter(source=>!managedIds.has(source.id));
const retainedLocations=(previous?.locations||[]).filter(location=>!managedIds.has(location.sourceId));
const output={retrievedAt,coverageNote:'Official-source voting site-type rows; consult each source for covered jurisdiction, election, freshness, and coordinate limits. National coverage is incomplete; failed sources retain prior rows with stale status.',sources:[...results.map(x=>x.source),...retainedSources],locations:[...results.flatMap(x=>x.locations),...retainedLocations]};
await fs.writeFile(file+'.tmp',JSON.stringify(output));await fs.rename(file+'.tmp',file);console.log(`Wrote ${output.locations.length} voting-site records to ${file}`);
